### ISSUE TITLE
DBLP filenames

### ISSUE THREAD

**Issue by allisonmorgan** [samfway/faculty_hiring#1]
**This might not be a code thing and might actually just be a data thing, so feel free to close if it's the latter.**

I'm hitting this error when I try to run: `load.load_all_publications(asst_faculty, dblp_dir)`:
```{python}
IOError: [Errno 2] No such file or directory: '/Users/allisonmorgan/Documents/faculty_hiring/publication_data/profiles_DBLP_Nov16/DBLP_=Ccedil=etintemel:Ugur.pkl'
```
I'm running [this notebook](https://github.com/samfway/faculty_hiring/blob/master/notebooks-productivity/General_Trends_Over_Time.ipynb), but I think it's probably happening where ever  `load_all_publications` is called.

This issue is that an author's DBLP ID contains ":", which shouldn't be allowed in filenames. (It's looking for the file that is actually called `DBLP_=Ccedil=etintemel_Ugur.pkl`.) I thought I could just throw a `f['dblp'].replace(":", "_")` [here](https://github.com/samfway/faculty_hiring/blob/master/parse/load.py#L78). That fixes the error on that faculty member, but then I get a different error:

```{python}
IOError: [Errno 2] No such file or directory: '/Users/allisonmorgan/Documents/faculty_hiring/publication_data/profiles_DBLP_Nov16/DBLP_Ahn_Gail=Joon.pkl'
```

It seems that just replacing all colons with underscores won't quite work because the file above is actually be called `DBLP_Ahn/Gail=Joon.pkl`.

**Comment by allisonmorgan** [comment]
Oh nevermind! It was a data thing. Downloaded the recent folder of DBLP profiles from Dropbox and we're good to go. Good work Sam! 😄

**Comment by samfway** [comment]
Pheeew haha :D
